name: Publish | Crates
on: workflow_dispatch
jobs:
  create-cargo-release:
    name: Publish to cargo
    environment: crates
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Update apt"
        run: sudo apt-get update -y
      - name: Install cargo
        run: sudo apt-get install -y cargo
      - name: Publish
        run: cargo publish --token  ${{ secrets.CRATES_TOKEN }}
      - name: Logout
        run: cargo logout
